# MPV Configuration
hwdec=auto-safe
save-position-on-quit=yes
autofit-larger=85%x85%
cursor-autohide=1000
volume=100
volume-max=150

# OSD Styling (Catppuccin Macchiato font colors)
osd-font="JetBrainsMono Nerd Font"
osd-font-size=26
osd-color="#cdd6f4"
osd-border-color="#181825"
osd-border-size=2
osd-bar-h=3
osd-bar-w=60
