[mgr]
ratio = [1, 3, 4]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 1000
max_height = 1000
cache_dir = ""
image_filter = "lanczos3"
image_quality = 85
sixel_fraction = 15

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', block = true, desc = "Editor" },
]
play = [
    { run = 'mpv "$@"', block = true, orphan = false, desc = "Play with mpv" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open with default application" },
]

[open]
rules = [
    { name = "*.{mp4,mkv,webm,avi,mov,m4v,mp3,flac,wav}", use = [ "play", "open" ] },
    { mime = "video/*", use = [ "play", "open" ] },
    { mime = "audio/*", use = [ "play", "open" ] },
    { mime = "text/*", use = [ "edit", "open" ] },
    { mime = "application/json", use = [ "edit", "open" ] },
    { name = "*", use = [ "open" ] },
]
