#!/usr/bin/env bash

xrdb -merge $HOME/.Xdefaults &
xrdb -merge $HOME/.Xresources &

(ps x | grep bspswallow | grep -v grep) || bspswallow &

###---WORKSPACES---###
# font needed "forkawesome"
# WS1=
# WS2=
# WS3=
# WS4=
WS1=1
WS2=2
WS3=3
WS4=4

# WS5=
# WS6=
# WS7=
# WS8=
# WS9=

WS5=5
WS6=6
WS7=7
WS8=8
WS9=9

###---MONITORS---###
connected_monitor_count=$(xrandr | grep " connected " | awk "{ print$1 }" | wc -l )

# if [ $connected_monitor_count -gt 1 ]; then
    bspc monitor DP-1 -d $WS1 $WS2 $WS3 $WS4 $WS5 
    bspc monitor HDMI-0 -d $WS6 $WS7 $WS8 $WS9
# else
    # bspc monitor -d $WS1 $WS2 $WS3 $WS4 $WS5 $WS6 $WS7 $WS8 $WS9
# fi

#### BSPWM configuration ####
# bspc config border_radius               8
bspc config border_width                  1
bspc config window_gap                    5
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-left_DP-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-right_HDMI-0)

## -------- Rules ----------------------##
bspc rule -a Skype  desktop=$WS9 state=tiled
bspc rule -a Mailspring desktop=$WS9 state=tiled follow=on
bspc rule -a Thunderbird desktop=$WS9

bspc rule -a qBittorrent desktop=$WS8 follow=on
# bspc rule -a "xdman-Main" desktop=$WS8 follow=on
bspc rule -a Transmission-gtk desktop=$WS8 follow=on
# bspc rule -a Upwork desktop=$WS5 follow=on
bspc rule -a "com.freelancer.workspace.launcher.Bootstrap" desktop=$WS5
bspc rule -a Hubstaff desktop=$WS5 state=floating follow=on


autostart
