#! /bin/sh

xrdb -merge $HOME/.Xdefaults &
xrdb -merge $HOME/.Xresources &
sxhkd &
$HOME/.config/polybar/launch.sh


(ps x | grep bspswallow | grep -v grep) || bspswallow &

###---WORKSPACES---###
# font needed "forkawesome"
WS1=
WS2=
WS3=
WS4=

WS6=
WS7=
WS8=
WS9=
WS0=


###---MONITORS---###
bspc monitor DP-1 -d $WS1 $WS2 $WS4
bspc monitor HDMI-0 -d $WS6 $WS7 $WS8 $WS9 $WS0


###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#e74c3c"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"


###---Monitor And Desktop Settings----###
bspc config top_padding 42
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10


## -------- Rules ----------------------##
bspc rule -a Skype  desktop=$WS0 state=tiled
bspc rule -a Mailspring desktop=$WS0 state=tiled follow=on
bspc rule -a Thunderbird desktop=$WS0

bspc rule -a qBittorrent desktop=$WS9 follow=on
bspc rule -a Transmission-gtk desktop=$WS9 follow=on
bspc rule -a Upwork desktop=$WS7 state=floating follow=on
bspc rule -a "com.freelancer.workspace.launcher.Bootstrap" desktop=$WS7 state=floating
